Ensure set_or_def picks a path
 - Otherwise use of iptables gets confused
 - Remove quotes from around command usage so parameters passed correctly
 - Fixes issues from commit 8bc274b3715dd340578647a987992dbddafea3b5

diff --git a/sbin/sanewall.in b/sbin/sanewall.in
--- a/sbin/sanewall.in
+++ b/sbin/sanewall.in
@@ -123,9 +123,11 @@ both() {
 export PATH="${PATH}:/bin:/usr/bin:/sbin:/usr/sbin"
 
 find_exe() {
-	local prog="$1"
-	set -- $prog
+	local cmd="$1"
+	set -- $cmd
 	local name="$1"
+	shift
+	local args="$@"
 
 	if [ "$name" = ":" ]; then echo ":"; return 0; fi
 
@@ -134,7 +136,14 @@ find_exe() {
 	for dir in "$@"
 	do
 		if [ ! "$dir" ]; then dir="."; fi
-		if [ -x "$dir/$name" ]; then echo "$prog"; return 0; fi
+		if [ -x "$dir/$name" ]; then
+			if [ "$args" ]; then
+				echo "$dir/$name $args"
+			else
+				echo "$dir/$name"
+			fi
+			return 0
+		fi
 	done
 	return 1
 }
@@ -154,14 +163,14 @@ set_or_def() {
 		esac
 	else
 		case "$2" in
-			/*) if [ -x "$2" ]; then value="$2"; fi ;;
-			'@'*) value="$3" ;;
-			*) value=$(find_exe "$2") ;;
+			/*) want="$2"; if [ -x "$2" ]; then value="$2"; fi ;;
+			'@'*) want="$3"; value=$(find_exe "$want") ;;
+			*) want="$2"; value=$(find_exe "$want") ;;
 		esac
 
 		if [ ! "$value" ]
 		then
-			echo "Missing required command: $1 (wanted $2)"
+			echo "Missing required command: $1 (wanted $want)"
 			exit 1
 		fi
 	fi
@@ -181,7 +190,7 @@ set_or_def FIND_CMD "@FIND_CMD@" "find"
 set_or_def FOLD_CMD "@FOLD_CMD@" "fold"
 set_or_def GREP_CMD "@GREP@" "grep"
 set_or_def HEAD_CMD "@HEAD_CMD@" "head"
-set_or_def INSMOD_CMD "@INSMOD_CMD@" "modprobe"
+set_or_def INSMOD_CMD "@INSMOD_CMD@" "modprobe -q"
 set_or_def IP6TABLES_CMD "@IP6TABLES_CMD@" "ip6tables"
 set_or_def IP6TABLES_RESTORE_CMD "@IP6TABLES_RESTORE_CMD@" "ip6tables-restore"
 set_or_def IP6TABLES_SAVE_CMD "@IP6TABLES_SAVE_CMD@" "ip6tables-save"
@@ -217,7 +226,7 @@ then
 fi
 
 modprobe_cmd() {
-	"${INSMOD_CMD}" "${@}"
+	${INSMOD_CMD} "${@}"
 	status=$?
 	if [ $status -eq 17 ]
 	then
@@ -238,11 +247,11 @@ iptables_cmd() {
 
 	if [ "$IPVER" = "ipv4" ]
 	then
-		"${IPTABLES_CMD}" "$@"
+		${IPTABLES_CMD} "$@"
 		status=$?
 	elif [ "$IPVER" = "ipv6" ]
 	then
-		"${IP6TABLES_CMD}" "$@"
+		${IP6TABLES_CMD} "$@"
 		status=$?
 	else
 		local status4=0
@@ -283,8 +292,8 @@ iptables_cmd() {
 		elif [ $host_next -eq 1 ]
 		then
 			host_next=0
-                        local not4=`"${IPTABLES_CMD}" -D INPUT -s "$i" -d "$i" -g NONEXIST 2>&1 | ${GREP_CMD} "not found"`
-                        local not6=`"${IP6TABLES_CMD}" -D INPUT -s "$i" -d "$i" -g NONEXIST 2>&1 | ${GREP_CMD} "not found"`
+                        local not4=`${IPTABLES_CMD} -D INPUT -s "$i" -d "$i" -g NONEXIST 2>&1 | ${GREP_CMD} "not found"`
+                        local not6=`${IP6TABLES_CMD} -D INPUT -s "$i" -d "$i" -g NONEXIST 2>&1 | ${GREP_CMD} "not found"`
 			if [ ! "$not4" -o ! "$not6" ]
 			then
 				# Use the output of the rule check command to
@@ -350,12 +359,12 @@ iptables_cmd() {
 
 		if [ $ipv6_ok -eq 1 ]
 		then
-			"${IP6TABLES_CMD}" "$@"
+			${IP6TABLES_CMD} "$@"
 			status6=$?
 		fi
 		if [ $ipv4_ok -eq 1 ]
 		then
-			"${IPTABLES_CMD}" "$@"
+			${IPTABLES_CMD} "$@"
 			status4=$?
 		fi
 		if [ ${status6} -ne 0 ]
@@ -376,7 +385,7 @@ iptables_save_cmd() {
 	if [ "$IPVER" = "ipv4" -o  "$IPVER" = "both" ]
 	then
 		echo "#IPV4-START"
-		"${IPTABLES_SAVE_CMD}" "${@}"
+		${IPTABLES_SAVE_CMD} "${@}"
 		status4=$?
 		echo "#IPV4-END"
 	fi
@@ -384,7 +393,7 @@ iptables_save_cmd() {
 	if [ "$IPVER" = "ipv6" -o  "$IPVER" = "both" ]
 	then
 		echo "#IPV6-START"
-		"${IP6TABLES_SAVE_CMD}" "$@"
+		${IP6TABLES_SAVE_CMD} "$@"
 		status6=$?
 		echo "#IPV6-END"
 	fi
@@ -407,14 +416,14 @@ iptables_restore_cmd() {
 	if [ "$IPVER" = "ipv4" -o  "$IPVER" = "both" ]
 	then
 		${SED_CMD} -ne '/^#IPV4-START/,/^#IPV4-END/p' ${file} | \
-			"${IPTABLES_RESTORE_CMD}" "$@"
+			${IPTABLES_RESTORE_CMD} "$@"
 		status4=$?
 	fi
 
 	if [ "$IPVER" = "ipv6" -o  "$IPVER" = "both" ]
 	then
 		${SED_CMD} -ne '/^#IPV6-START/,/^#IPV6-END/p' ${file} | \
-			"${IP6TABLES_RESTORE_CMD}" "$@"
+			${IP6TABLES_RESTORE_CMD} "$@"
 		status6=$?
 	fi
 
@@ -434,7 +443,7 @@ SANEWALL_LOCK_FILE="/var/run/sanewall.lck"
 SANEWALL_LOCKED=
 
 sanewall_concurrent_run_lock() {
-	if [ "${FLOCK_CMD}" = ":" ]
+	if [ ${FLOCK_CMD} = ":" ]
 	then
 		# Time in secs to consider a lock stale
 		SANEWALL_LOCK_FILE_TIMEOUT=600
@@ -470,7 +479,7 @@ sanewall_concurrent_run_lock() {
 }
 
 sanewall_concurrent_run_unlock() {
-	case "${FLOCK_CMD}" in
+	case ${FLOCK_CMD} in
 		':')
 			if [ "${SANEWALL_LOCKED}" ]
 			then
@@ -563,7 +572,7 @@ SANEWALL_NOTIFICATION_PROGRAM=""
 syslog() {
 	local p="$1"; shift
 
-	"${LOGGER_CMD}" -p ${SANEWALL_SYSLOG_FACILITY}.$p -t "sanewall[$$]" "${@}"
+	${LOGGER_CMD} -p ${SANEWALL_SYSLOG_FACILITY}.$p -t "sanewall[$$]" "${@}"
 	return 0
 }
 
@@ -656,7 +665,7 @@ then
 	exit 1
 fi
 
-"${MKDIR_CMD}" "${SANEWALL_CHAINS_DIR}"			|| exit 1
+${MKDIR_CMD} "${SANEWALL_CHAINS_DIR}"			|| exit 1
 
 # prepare the file that will hold all modules to be loaded.
 # this is needed only when we are going to save the firewall
@@ -672,9 +681,9 @@ EOFMTL
 # Make sure we have a directory for our data.
 if [ ! -d "${SANEWALL_SPOOL_DIR}" ]
 then
-	"${MKDIR_CMD}" "${SANEWALL_SPOOL_DIR}"		|| exit 1
-	"${CHOWN_CMD}" root:root "${SANEWALL_SPOOL_DIR}"	|| exit 1
-	"${CHMOD_CMD}" 700 "${SANEWALL_SPOOL_DIR}"	|| exit 1
+	${MKDIR_CMD} "${SANEWALL_SPOOL_DIR}"		|| exit 1
+	${CHOWN_CMD} root:root "${SANEWALL_SPOOL_DIR}"	|| exit 1
+	${CHMOD_CMD} 700 "${SANEWALL_SPOOL_DIR}"	|| exit 1
 fi
 
 load_ips() {
@@ -2485,8 +2494,8 @@ do
 		continue
 	fi
 
-	n=`"${HEAD_CMD}" -n 1 "${f}" | "${CUT_CMD}" -d ':' -f 2`
-	"${EXPR_CMD}" ${n} + 0 >/dev/null 2>&1
+	n=`${HEAD_CMD} -n 1 "${f}" | ${CUT_CMD} -d ':' -f 2`
+	${EXPR_CMD} ${n} + 0 >/dev/null 2>&1
 	if [ $? -ne 0 ]
 	then
 		echo >&2 " >>> Ignoring service in '${SANEWALL_CONFIG_DIR}/services/${f}' due to malformed header."
@@ -2494,8 +2503,8 @@ do
 	then
 		echo >&2 " >>> Ignoring service '${SANEWALL_CONFIG_DIR}/services/${f}' due to incompatible API version."
 	else
-		n=`"${HEAD_CMD}" -n 1 "${f}" | "${CUT_CMD}" -d ':' -f 3`
-		"${EXPR_CMD}" ${n} + 0 >/dev/null 2>&1
+		n=`${HEAD_CMD} -n 1 "${f}" | ${CUT_CMD} -d ':' -f 3`
+		${EXPR_CMD} ${n} + 0 >/dev/null 2>&1
 		if [ $? -ne 0 ]
 		then
 			echo >&2 " >>> Ignoring service in '${SANEWALL_CONFIG_DIR}/services/${f}' due to malformed API minor number."
@@ -3217,7 +3226,7 @@ runcmd() {
 	"${cmd}" "$@" >${SANEWALL_OUTPUT}.log 2>&1
 	if [ "$SANEWALL_DEBUGGING" ]
 	then
-		"${CAT_CMD}" ${SANEWALL_OUTPUT}.log 1>&2
+		${CAT_CMD} ${SANEWALL_OUTPUT}.log 1>&2
 	fi
 	local r=$?
 	test ${r} -gt 0 && runtime_error ${check} ${r} ${line} "${cmd}" "$@"
@@ -3485,19 +3494,19 @@ fi
 if [ -z "${KERNEL_CONFIG}" -a -f "/lib/modules/`${UNAME_CMD} -r`/build/.config" ]
 then
 	KERNEL_CONFIG="/lib/modules/`${UNAME_CMD} -r`/build/.config"
-	"${CAT_CMD}" "${KERNEL_CONFIG}" >"${SANEWALL_DIR}/kcfg" || KERNEL_CONFIG=
+	${CAT_CMD} "${KERNEL_CONFIG}" >"${SANEWALL_DIR}/kcfg" || KERNEL_CONFIG=
 fi
 
 if [ -z "${KERNEL_CONFIG}" -a -f "/boot/config-`${UNAME_CMD} -r`" ]
 then
 	KERNEL_CONFIG="/boot/config-`${UNAME_CMD} -r`"
-	"${CAT_CMD}" "${KERNEL_CONFIG}" >"${SANEWALL_DIR}/kcfg" || KERNEL_CONFIG=
+	${CAT_CMD} "${KERNEL_CONFIG}" >"${SANEWALL_DIR}/kcfg" || KERNEL_CONFIG=
 fi
 
 if [ -z "${KERNEL_CONFIG}" -a -f "/usr/src/linux/.config" ]
 then
 	KERNEL_CONFIG="/usr/src/linux/.config"
-	"${CAT_CMD}" "${KERNEL_CONFIG}" >"${SANEWALL_DIR}/kcfg" || KERNEL_CONFIG=
+	${CAT_CMD} "${KERNEL_CONFIG}" >"${SANEWALL_DIR}/kcfg" || KERNEL_CONFIG=
 fi
 
 # Did we managed to find the kernel configuration?
@@ -3508,7 +3517,7 @@ then
 	# Load all the definitions for CONFIG_*_NF_* variables
 	# We grep what we care for, to make sure there is no garbage or malicious code
 	# in the file we will run.
-	"${CAT_CMD}" "${SANEWALL_DIR}/kcfg" | ${GREP_CMD} -e "^CONFIG_[A-Z0-9_]\+_NF_[A-Z0-9_]\+=[ynm]$" >"${SANEWALL_DIR}/kcfg.nf"
+	${CAT_CMD} "${SANEWALL_DIR}/kcfg" | ${GREP_CMD} -e "^CONFIG_[A-Z0-9_]\+_NF_[A-Z0-9_]\+=[ynm]$" >"${SANEWALL_DIR}/kcfg.nf"
 
 	# run it to get the variables
 	source "${SANEWALL_DIR}/kcfg.nf"
@@ -6260,7 +6269,7 @@ case "${arg}" in
 				echo
 				echo "--- MANGLE IPv4 ----------------------------------------------------------------"
 				echo
-				"${IPTABLES_CMD}" -t mangle -nxvL
+				${IPTABLES_CMD} -t mangle -nxvL
 			fi
 
 			if [ "${IPVER}" = "both" -o  "${IPVER}" = "ipv6" ]
@@ -6269,7 +6278,7 @@ case "${arg}" in
 				echo
 				echo "--- MANGLE IPv6 ----------------------------------------------------------------"
 				echo
-				"${IP6TABLES_CMD}" -t mangle -nxvL
+				${IP6TABLES_CMD} -t mangle -nxvL
 			fi
 
 			if [ "${IPVER}" = "both" -o  "${IPVER}" = "ipv4" ]
@@ -6278,7 +6287,7 @@ case "${arg}" in
 				echo
 				echo "--- NAT IPv4 -------------------------------------------------------------------"
 				echo
-				"${IPTABLES_CMD}" -t nat -nxvL
+				${IPTABLES_CMD} -t nat -nxvL
 			fi
 
 			if [ "${IPVER}" = "both" -o  "${IPVER}" = "ipv4" ]
@@ -6287,7 +6296,7 @@ case "${arg}" in
 				echo
 				echo "--- FILTER IPv4 ----------------------------------------------------------------"
 				echo
-				"${IPTABLES_CMD}" -nxvL
+				${IPTABLES_CMD} -nxvL
 			fi
 
 			if [ "${IPVER}" = "both" -o  "${IPVER}" = "ipv6" ]
@@ -6296,7 +6305,7 @@ case "${arg}" in
 				echo
 				echo "--- FILTER IPv6 ----------------------------------------------------------------"
 				echo
-				"${IP6TABLES_CMD}" -nxvL
+				${IP6TABLES_CMD} -nxvL
 			fi
 		) | ${PAGER_CMD}
 		exit $?
@@ -6857,15 +6866,15 @@ then
 	}
 
 	cd "${SANEWALL_DIR}"
-	"${MKDIR_CMD}" ports
-	"${MKDIR_CMD}" keys
+	${MKDIR_CMD} ports
+	${MKDIR_CMD} keys
 	cd ports
-	"${MKDIR_CMD}" tcp
-	"${MKDIR_CMD}" udp
+	${MKDIR_CMD} tcp
+	${MKDIR_CMD} udp
 
 	emit_version >&2
 
-	"${CAT_CMD}" >&2 <<EOF
+	${CAT_CMD} >&2 <<EOF
 Sanewall will now try to figure out its configuration file on this system.
 Please have all the services and network interfaces on this system running.
 
